# Generated by Django 4.2 on 2023-05-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-10-17'),
            preserve_default=False,
        ),
    ]
